# Day 4

# Data Wrangling

In [1]:
import pandas as pd
pd.set_option('precision', 2)
pd.set_option('display.max_columns', None)

### Add a Header

In [2]:
# Add header = None when there is no header in csv file
data = pd.read_csv('you.csv', header=None)

In [3]:
data

       0  1  2           3
0  Jason  1  6      writer
1  Betty  1  0      author
2   Lucy  2  2        chef
3   Fred  2  0    director
4  Cindy  1  0     stalker
5   Paul  1  1      reader
6  Peter  1  0   rich dude
7  Damon  2  0  journalist

In [4]:
# Practice with the Avengers Data
# read the CSV
avengers = pd.read_csv('characters.csv', header=None)

In [5]:
avengers

                  0        1    2    3
0           Ant-Man     good  100   32
1     Black Panther     good   88  100
2       Black Widow     good  100  100
3   Captain America     good   63  100
4    Captain Marvel     good  100   56
5         Daredevil     good   75   95
6          Deadpool  neutral   50  100
7    Doctor Strange     good  100   60
8             Groot     good   75   64
9          Iron Man     good  100   64
10          Hawkeye     good   50   80
11             Hulk     good   88   85
12             Loki      bad   88   56
13        Nick Fury     good   75  100
14        Red Skull      bad   75   80
15   Rocket Raccoon     good   50   64
16       Spider-Man     good   88   85
17             Thor     good   69   85
18           Thanos      bad   88   80
19           Ultron      bad   88   64
20           Violet     good   10   14
21           Vision     good  100   70
22      War Machine     good   63   85
23             Wasp     good   63   42

### Rename a column

In [6]:
data

       0  1  2           3
0  Jason  1  6      writer
1  Betty  1  0      author
2   Lucy  2  2        chef
3   Fred  2  0    director
4  Cindy  1  0     stalker
5   Paul  1  1      reader
6  Peter  1  0   rich dude
7  Damon  2  0  journalist

In [7]:
data.columns

Int64Index([0, 1, 2, 3], dtype='int64')

In [8]:
# Rename the columns
data = data.rename(columns = {0 : 'Name', 1 : 'First Appearance',
                              2 : 'Kills', 3 : 'Profession'})

In [9]:
data

    Name  First Appearance  Kills  Profession
0  Jason                 1      6      writer
1  Betty                 1      0      author
2   Lucy                 2      2        chef
3   Fred                 2      0    director
4  Cindy                 1      0     stalker
5   Paul                 1      1      reader
6  Peter                 1      0   rich dude
7  Damon                 2      0  journalist

In [10]:
# Practice with the Avengers Data
# Change Name, Alignment, Intelligence, Combat

In [11]:
avengers = avengers.rename(columns={0 : "Name", 1 : "Alignment", 2: "Intelligence", 3: "Combat"})

In [12]:
avengers

               Name Alignment  Intelligence  Combat
0           Ant-Man      good           100      32
1     Black Panther      good            88     100
2       Black Widow      good           100     100
3   Captain America      good            63     100
4    Captain Marvel      good           100      56
5         Daredevil      good            75      95
6          Deadpool   neutral            50     100
7    Doctor Strange      good           100      60
8             Groot      good            75      64
9          Iron Man      good           100      64
10          Hawkeye      good            50      80
11             Hulk      good            88      85
12             Loki       bad            88      56
13        Nick Fury      good            75     100
14        Red Skull       bad            75      80
15   Rocket Raccoon      good            50      64
16       Spider-Man      good            88      85
17             Thor      good            69      85
18           Thanos       bad            88      80
19           Ultron       bad            88      64
20           Violet      good            10      14
21           Vision      good           100      70
22      War Machine      good            63      85
23             Wasp      good            63      42

### Setting an Index

In [13]:
data

    Name  First Appearance  Kills  Profession
0  Jason                 1      6      writer
1  Betty                 1      0      author
2   Lucy                 2      2        chef
3   Fred                 2      0    director
4  Cindy                 1      0     stalker
5   Paul                 1      1      reader
6  Peter                 1      0   rich dude
7  Damon                 2      0  journalist

In [14]:
# set a column as the index of the dataframe
data = data.set_index('Name')

In [15]:
data

       First Appearance  Kills  Profession
Name
Jason                 1      6      writer
Betty                 1      0      author
Lucy                  2      2        chef
Fred                  2      0    director
Cindy                 1      0     stalker
Paul                  1      1      reader
Peter                 1      0   rich dude
Damon                 2      0  journalist

### Accessing a column

In [16]:
# Access a row
data.loc['Jason']

First Appearance         1
Kills                    6
Profession          writer
Name: Jason, dtype: object

In [17]:
# Accesss a row
data.loc['Peter']

First Appearance            1
Kills                       0
Profession          rich dude
Name: Peter, dtype: object

In [18]:
# Practice with the Avengers Data
# Access any superhero character data

In [19]:
avengers.head(5)

              Name Alignment  Intelligence  Combat
0          Ant-Man      good           100      32
1    Black Panther      good            88     100
2      Black Widow      good           100     100
3  Captain America      good            63     100
4   Captain Marvel      good           100      56

In [20]:
avengers = avengers.set_index('Name')

In [21]:
avengers.loc['Black Widow']

Alignment       good
Intelligence     100
Combat           100
Name: Black Widow, dtype: object

In [22]:
# Specify a row and index
data.loc['Peter', 'Profession']

'rich dude'

In [23]:
# Practice with the Avengers Data
# Access Hulk's "Combat" score

In [24]:
avengers.loc['Hulk', 'Combat']

85

### Vector Addition

In [28]:
data

       First Appearance  Kills  Profession  Score
Name
Jason                 1      6      writer    3.5
Betty                 1      0      author    0.5
Lucy                  2      2        chef    2.0
Fred                  2      0    director    1.0
Cindy                 1      0     stalker    0.5
Paul                  1      1      reader    1.0
Peter                 1      0   rich dude    0.5
Damon                 2      0  journalist    1.0

In [26]:
data['Kills']

Name
Jason    6
Betty    0
Lucy     2
Fred     0
Cindy    0
Paul     1
Peter    0
Damon    0
Name: Kills, dtype: int64

In [27]:
# Uses vector addition to add a new column
data['Score'] = (data['First Appearance'] + data['Kills']) / 2

In [29]:
# Practice with the Avengers Data
# Create a Column that takes the average of both the "Intelligence" and "Combat" scores

In [33]:
avengers.head(5)

                Alignment  Intelligence  Combat  Score  Average Score
Name
Ant-Man              good           100      32   66.0           66.0
Black Panther        good            88     100   94.0           94.0
Black Widow          good           100     100  100.0          100.0
Captain America      good            63     100   81.5           81.5
Captain Marvel       good           100      56   78.0           78.0

In [32]:
avengers['Average Score'] = (avengers['Intelligence'] + avengers['Combat']) / 2

### Unique Values

In [34]:
data

       First Appearance  Kills  Profession  Score
Name
Jason                 1      6      writer    3.5
Betty                 1      0      author    0.5
Lucy                  2      2        chef    2.0
Fred                  2      0    director    1.0
Cindy                 1      0     stalker    0.5
Paul                  1      1      reader    1.0
Peter                 1      0   rich dude    0.5
Damon                 2      0  journalist    1.0

In [35]:
# Unique values in the column
# Returns a List
print(data['First Appearance'].unique())

[1 2]

In [36]:
avengers.head()

                Alignment  Intelligence  Combat  Score  Average Score
Name
Ant-Man              good           100      32   66.0           66.0
Black Panther        good            88     100   94.0           94.0
Black Widow          good           100     100  100.0          100.0
Captain America      good            63     100   81.5           81.5
Captain Marvel       good           100      56   78.0           78.0

In [37]:
# Practice with the Avengers Data
# Create a Column that gets the unique "Alignment" values
avengers['Alignment'].unique()

array(['good', 'neutral', 'bad'], dtype=object)

### Sorting Values

In [46]:
data

       First Appearance  Kills  Profession  Score
Name
Betty                 1      0      author    0.5
Cindy                 1      0     stalker    0.5
Peter                 1      0   rich dude    0.5
Paul                  1      1      reader    1.0
Jason                 1      6      writer    3.5
Damon                 2      0  journalist    1.0
Fred                  2      0    director    1.0
Lucy                  2      2        chef    2.0

In [41]:
# axis = 0 is for the rows
# axis = 1 is for the columns
# ascending is reversing the direction it is ordered
data = data.sort_index(axis = 1, ascending = True)
data = data.sort_index(axis = 0, ascending = True)

In [45]:
# You can list the data set using multiple factors
# Inplace means that the changes are assigned to the dataframe
# without having to equate the values to the data
# ex: data = data.somthing...
data.sort_values(by = ['First Appearance', 'Kills'], ascending = True, inplace = True)

In [47]:
avengers.head()

                Alignment  Intelligence  Combat  Score  Average Score
Name
Ant-Man              good           100      32   66.0           66.0
Black Panther        good            88     100   94.0           94.0
Black Widow          good           100     100  100.0          100.0
Captain America      good            63     100   81.5           81.5
Captain Marvel       good           100      56   78.0           78.0

In [55]:
# Practice with the Avengers Data
# Sort values by Intelligence and Combat
# avengers.sort_values(by=['Intelligence', 'Combat'], ascending=False)
avengers.sort_values(by=['Average Score'], ascending=False)

                Alignment  Intelligence  Combat  Score  Average Score
Name
Black Widow          good           100     100  100.0          100.0
Black Panther        good            88     100   94.0           94.0
Nick Fury            good            75     100   87.5           87.5
Hulk                 good            88      85   86.5           86.5
Spider-Man           good            88      85   86.5           86.5
Daredevil            good            75      95   85.0           85.0
Vision               good           100      70   85.0           85.0
Thanos                bad            88      80   84.0           84.0
Iron Man             good           100      64   82.0           82.0
Captain America      good            63     100   81.5           81.5
Doctor Strange       good           100      60   80.0           80.0
Captain Marvel       good           100      56   78.0           78.0
Red Skull             bad            75      80   77.5           77.5
Thor                 good            69      85   77.0           77.0
Ultron                bad            88      64   76.0           76.0
Deadpool          neutral            50     100   75.0           75.0
War Machine          good            63      85   74.0           74.0
Loki                  bad            88      56   72.0           72.0
Groot                good            75      64   69.5           69.5
Ant-Man              good           100      32   66.0           66.0
Hawkeye              good            50      80   65.0           65.0
Rocket Raccoon       good            50      64   57.0           57.0
Wasp                 good            63      42   52.5           52.5
Violet               good            10      14   12.0           12.0

### Boolean Indexing

In [56]:
data

       First Appearance  Kills  Profession  Score
Name
Betty                 1      0      author    0.5
Cindy                 1      0     stalker    0.5
Peter                 1      0   rich dude    0.5
Paul                  1      1      reader    1.0
Jason                 1      6      writer    3.5
Damon                 2      0  journalist    1.0
Fred                  2      0    director    1.0
Lucy                  2      2        chef    2.0

In [57]:
# Called Boolean Indexing
# Allows us to query a dataframe
# Is a series object
print(data['Kills'] > 1)

Name
Betty    False
Cindy    False
Peter    False
Paul     False
Jason     True
Damon    False
Fred     False
Lucy      True
Name: Kills, dtype: bool

In [58]:
# The where keyword argument is used for boolean indexing
dangerous = data.where(data['Kills'] >= 2)

In [59]:
dangerous

       First Appearance  Kills Profession  Score
Name
Betty               NaN    NaN        NaN    NaN
Cindy               NaN    NaN        NaN    NaN
Peter               NaN    NaN        NaN    NaN
Paul                NaN    NaN        NaN    NaN
Jason               1.0    6.0     writer    3.5
Damon               NaN    NaN        NaN    NaN
Fred                NaN    NaN        NaN    NaN
Lucy                2.0    2.0       chef    2.0

### Drop null values

In [60]:
# Drop null values
dangerous.dropna(inplace = True)

In [61]:
dangerous

       First Appearance  Kills Profession  Score
Name
Jason               1.0    6.0     writer    3.5
Lucy                2.0    2.0       chef    2.0

### Bitwise Operators

In [62]:
dangerous = data[data['Kills'] >= 2]

In [68]:
dangerous

      First Appearance  Kills Profession  Score
Name
Lucy                 2      2       chef    2.0

In [65]:
# and in python: &
# or in python: |

In [66]:
# & to combine multiple conditions
# | to use a bitwise OR
dangerous = data[(data['Kills'] >= 2) & (data['First Appearance'] == 2)]

In [67]:
avengers.head()

               Alignment  Intelligence  Combat  Score  Average Score
Name
Violet              good            10      14   12.0           12.0
Rocket Raccoon      good            50      64   57.0           57.0
Hawkeye             good            50      80   65.0           65.0
Deadpool         neutral            50     100   75.0           75.0
Wasp                good            63      42   52.5           52.5

In [71]:
# Practice with the Avengers Data
# Get all characters who have both a combat score and intelligence score of 100

avengers100 = avengers[(avengers['Combat'] == 100) & (avengers['Intelligence'] == 100)]

In [72]:
avengers100

            Alignment  Intelligence  Combat  Score  Average Score
Name
Black Widow      good           100     100  100.0          100.0

### Average for a Column

In [73]:
data

       First Appearance  Kills  Profession  Score
Name
Betty                 1      0      author    0.5
Cindy                 1      0     stalker    0.5
Peter                 1      0   rich dude    0.5
Paul                  1      1      reader    1.0
Jason                 1      6      writer    3.5
Damon                 2      0  journalist    1.0
Fred                  2      0    director    1.0
Lucy                  2      2        chef    2.0

In [74]:
data['Kills'].describe()

count    8.00
mean     1.12
std      2.10
min      0.00
25%      0.00
50%      0.00
75%      1.25
max      6.00
Name: Kills, dtype: float64

In [75]:
# Average for a column
print(data['Kills'].mean())

1.125

In [76]:
# Practice with the Avengers Data
# Get the average combat score
avengers['Combat'].mean()

73.375

### Column Indexes

In [77]:
data

       First Appearance  Kills  Profession  Score
Name
Betty                 1      0      author    0.5
Cindy                 1      0     stalker    0.5
Peter                 1      0   rich dude    0.5
Paul                  1      1      reader    1.0
Jason                 1      6      writer    3.5
Damon                 2      0  journalist    1.0
Fred                  2      0    director    1.0
Lucy                  2      2        chef    2.0

In [78]:
# columns we would like to keep using
columns_wanted = ['Kills', 'Profession']
new_data = data[columns_wanted]

In [79]:
data['Score']

Name
Betty    0.5
Cindy    0.5
Peter    0.5
Paul     1.0
Jason    3.5
Damon    1.0
Fred     1.0
Lucy     2.0
Name: Score, dtype: float64

In [80]:
new_data

       Kills  Profession
Name
Betty      0      author
Cindy      0     stalker
Peter      0   rich dude
Paul       1      reader
Jason      6      writer
Damon      0  journalist
Fred       0    director
Lucy       2        chef

In [81]:
data

       First Appearance  Kills  Profession  Score
Name
Betty                 1      0      author    0.5
Cindy                 1      0     stalker    0.5
Peter                 1      0   rich dude    0.5
Paul                  1      1      reader    1.0
Jason                 1      6      writer    3.5
Damon                 2      0  journalist    1.0
Fred                  2      0    director    1.0
Lucy                  2      2        chef    2.0

In [82]:
# Resets the column indexes so the names are 0,1,2...
data = data.reset_index()

In [83]:
data

    Name  First Appearance  Kills  Profession  Score
0  Betty                 1      0      author    0.5
1  Cindy                 1      0     stalker    0.5
2  Peter                 1      0   rich dude    0.5
3   Paul                 1      1      reader    1.0
4  Jason                 1      6      writer    3.5
5  Damon                 2      0  journalist    1.0
6   Fred                 2      0    director    1.0
7   Lucy                 2      2        chef    2.0

In [84]:
# Practice with the Avengers Data
# Create a dataframe that only has the name and the combined score
avengers = avengers.reset_index()
avengers[['Name', 'Average Score']].sort_values('Average Score', ascending=False)

               Name  Average Score
23      Black Widow          100.0
17    Black Panther           94.0
11        Nick Fury           87.5
15             Hulk           86.5
16       Spider-Man           86.5
10        Daredevil           85.0
22           Vision           85.0
14           Thanos           84.0
21         Iron Man           82.0
6   Captain America           81.5
20   Doctor Strange           80.0
19   Captain Marvel           78.0
9         Red Skull           77.5
7              Thor           77.0
13           Ultron           76.0
3          Deadpool           75.0
5       War Machine           74.0
12             Loki           72.0
8             Groot           69.5
18          Ant-Man           66.0
2           Hawkeye           65.0
1    Rocket Raccoon           57.0
4              Wasp           52.5
0            Violet           12.0

### Indexes

In [85]:
# Set the indexes of our dataframe using multiple attributes
# Generally make one over-arch the other
data = data.set_index(['First Appearance', 'Kills']).sort_index()

In [86]:
# Returns all the indexes as tuples
# Will list all even if redundant - need to use 'unique' if
# you want the unique indices
print(data.index, end = '\n\n')

MultiIndex([(1, 0),
            (1, 0),
            (1, 0),
            (1, 1),
            (1, 6),
            (2, 0),
            (2, 0),
            (2, 2)],
           names=['First Appearance', 'Kills'])

In [87]:
# You can also choose the first index and another column
print(data.loc[1, 'Score'].mean())

1.2

In [88]:
# Practice with the Avengers Data
# Index data into alignment and name
# Print out teh indexes
# Find the mean of the intelligence score for all three categories

# Dataframe Aggregations

### Group By

In [89]:
import pandas as pd
pd.set_option('precision', 2)
pd.set_option('display.max_columns', None)

In [90]:
df = pd.read_csv('divergent.csv')
df

FileNotFoundError: ignored

In [ ]:
df['original'] = ['y', 'n', 'y', 'n' , 'n', 'y', 'n' , 'n', 'n', 'y']
df

In [ ]:
#df = df.set_index(['faction', 'name'])
df = df.set_index(['faction', 'name']).sort_index()

In [ ]:
df.loc['dauntless'].mean()

In [ ]:
df.groupby('faction')['brave'].mean()

In [ ]:
# Practice with the Avengers Data
# Find the mean of the intelligence score for all three categories

In [ ]:
df.groupby(level = 'faction').mean()

In [ ]:
df.groupby(['faction', 'original']).mean()

In [ ]:
df.groupby(['faction', 'original']).agg(['count', 'mean', 'std'])

In [ ]:
# Practice with the Avengers Data
# Find the count, mean, std of the intelligence score for all three categories

In [ ]:
def score(score):

    if score.mean() > 85:
        return 'very'
    else:
        return 'eh'

In [ ]:
def passed(score):

    if score.mean() > 60:
        return 'passed'
    else:
        return 'failed'

### Aggregation

In [ ]:
df.groupby('faction').agg(score)

In [ ]:
df.groupby('faction').agg(['count', 'mean', 'std', score])

In [ ]:
df.groupby('faction').agg({'kind' : passed, 'brave' : score,
                                 'smart' : score, 'honest' : score,
                                 'selfless' : score})